version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://myappuser:mysecretpassword@db:5432/myappdb
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: myappuser 
      POSTGRES_PASSWORD: mysecretpassword 
      POSTGRES_DB: myappdb 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/app:/app
    depends_on:
      - backend
      - db
volumes:
  postgres_data:
    driver: local